### ISSUE TITLE
Dependence on deprecated <mfenced> element 

### ISSUE THREAD

**Issue by Steve-Noble** [tsengwoody/Access8Math#22]
Access8Math reading of container structures depends on the deprecated &lt;mfenced&gt; element. This element is rarely found on the web, and developers are advised to use the &lt;mrow&gt; and &lt;mo&gt; elements instead as it has been deprecated from the MathML spec. See [this discussion](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced) for detail. However, Access8Math does not recognize this very common construction, and reads nothing when parentheses or vertical bars surround an expression. See this [sample page](https://muh204-75.usite.pro/ACT_Test_Page.htm) for examples of the common authoring practice for both parenthetical statements and absolute value constructions which do not used the deprecated <mfenced> element.

**Comment by thrintuim** [comment]
Not sure if this held true in 2021 but based on my testing this past week the announcement of fences in the `mrow` `mo` construction is dependent upon the punctuation verbosity setting in NVDA (I've observed the same in JAWS). If you turn the punctuation to "all" the fences will be announced. Same for `mfenced` elements with `@open` and `@close`. In the `mfenced` construction the default math rule is "open parentheses", the content of the `mfenced` element, and then "close parentheses". If `@open` and/or `@close` exist their content will be inserted before "open parentheses" and before "close parentheses" respectively, which may or may not be desirable (I think this announcement is confusing). I also noticed that Access8Math doesn't announce the default parenthesis when only `@open` or `@close` exist. A construct like [1,2) would be "left bracket open parentheses 1 2 close parentheses" rather than "left bracket open parentheses 1 2 right parenthesis close parentheses". The default parentheses are only "correctly" announced when both `@open` and `@close` are absent.
