### ISSUE TITLE
Access8math -3.0-Dev, The Math Rules dialog cannot be opened again

### ISSUE THREAD

**Issue by cary-rowen** [tsengwoody/Access8Math#26]
### Steps to reproduce:
1. git pull the latest repo ;
2. Execute scons to build add-on;
3. Install add-on  that have been built;
4. After restarting NVDA, go to “Tools” ➡ “Access8Math” ➡ “Localization” ➡ “Mathematical rules”;
5. Click;
6. Click the "OK" button in the dialog;

### Actual behavior:
Nothing happens, and the dialog box is not closed.If you cancel at this time, you cannot finish reopening the dialog box.

### Expected behavior:
The settings should be applied, the dialog should be closed, and the dialog can be opened again.
#### NVDA installed/portable/running from source:
installed

#### NVDA version:
NVDA2020.4

#### Windows version:
Windows 10 20H2 (64Bit) build 19042.985

### Other questions
It seems that there are problems with the interaction of many settings dialogs, eg, it is currently not possible to change the display language of add-ons.

**Comment by Futyn-Maker** [comment]
Hello! Have you changed some Math rules using the add-on UI before this problem has come? Try to delete files with 'user' prefix in folder of your language, so math.user.rules and unicode.user.dic and then restart NVDA.
  
  If it will help, I can talk about another problem: Sometimes something goes wrong with rule-file when editing via UI, and because of this errors Access8Math doesn't work correctly. I've faced with this when making the Russian translation of rules, still I use a text editor for editing rules-files.

**Comment by cary-rowen** [comment]
Thanks for your help, but this does not solve the problem.
@Futyn-Maker

**Comment by tsengwoody** [comment]
I fixed this bug please test it.

**Comment by cary-rowen** [comment]
Yes, it has been fixed. But the language change still seems to be invalid.
I want to change the interface language from simplified Chinese to English, which seems to be unsuccessful.

**Comment by tsengwoody** [comment]
The interface language setting should to be changed from NVDA setting instead of the language setting in Access8Math.
The language setting in Access8Math is used to parse/read MathML content only.

**Comment by cary-rowen** [comment]
Sorry, I misunderstood. The repair is effective. The issue can now be closed.
