### ISSUE TITLE
The addon reads the symbols in English even if set to Italian.

### ISSUE THREAD

**Issue by Ambro86** [tsengwoody/Access8Math#91]
Hi, first of all thank you for the project. Only one thing. By installing the addon, and setting the language to Italian, the addon reads all the symbols in English. How come? The only way I was able to make it read in Italian was by setting mathplayer as the reading engine.

**Comment by tsengwoody** [comment]
Hi, first of all, thank you for your feedback. Regarding the issue you mentioned, where the addon reads symbols in English even after setting the language to Italian, this is because Italian is not currently included in Access8Math. Consequently, the settings in Access8Math cannot be adjusted to Italian. I assume you used the "New language" dialog from the localization menu but did not modify the math rules/Unicode dictionary. The "New language" dialog function merely adds a template file using English as the example. To address this, you will need to specifically localize the file for Italian. For detailed instructions, please consult the readme [localization section](https://github.com/tsengwoody/Access8Math#localization).
